<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5023" started-at="2022-01-30T11:37:46 IST" finished-at="2022-01-30T11:37:51 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5023" started-at="2022-01-30T11:37:46 IST" finished-at="2022-01-30T11:37:51 IST">
      <class name="tests.rest.TC002_GetIncident">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:tests.rest.TC002_GetIncident@1b26f7b2]" name="beforeSuite" is-config="true" duration-ms="452" started-at="2022-01-30T11:37:45 IST" finished-at="2022-01-30T11:37:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setValues()[pri:0, instance:tests.rest.TC002_GetIncident@1b26f7b2]" name="setValues" is-config="true" duration-ms="0" started-at="2022-01-30T11:37:46 IST" finished-at="2022-01-30T11:37:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setValues -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:tests.rest.TC002_GetIncident@1b26f7b2]" name="beforeClass" is-config="true" duration-ms="1" started-at="2022-01-30T11:37:46 IST" finished-at="2022-01-30T11:37:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:tests.rest.TC002_GetIncident@1b26f7b2]" name="beforeMethod" is-config="true" duration-ms="4" started-at="2022-01-30T11:37:46 IST" finished-at="2022-01-30T11:37:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="getIncident()[pri:0, instance:tests.rest.TC002_GetIncident@1b26f7b2]" name="getIncident" duration-ms="4998" started-at="2022-01-30T11:37:46 IST" finished-at="2022-01-30T11:37:51 IST">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at lib.utils.HTMLReporter.reportRequest(HTMLReporter.java:102)
at lib.rest.RESTAssuredBase.verifyResponseCode(RESTAssuredBase.java:206)
at tests.rest.TC002_GetIncident.getIncident(TC002_GetIncident.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getIncident -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:tests.rest.TC002_GetIncident@1b26f7b2]" name="afterMethod" is-config="true" duration-ms="0" started-at="2022-01-30T11:37:51 IST" finished-at="2022-01-30T11:37:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:tests.rest.TC002_GetIncident@1b26f7b2]" name="afterSuite" is-config="true" duration-ms="208" started-at="2022-01-30T11:37:51 IST" finished-at="2022-01-30T11:37:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- tests.rest.TC002_GetIncident -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
